name: Publish AngleParse
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Install Pester module
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Install-Module -Name Pester -RequiredVersion 5.7.1 -Force -SkipPublisherCheck -Scope CurrentUser
      - name: dotnet test
        run: |
          dotnet test ./AngleParse.Test/AngleParse.Test.csproj -c Release
      - name: run pester tests
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module Pester -Force
          Invoke-Pester -Path ./AngleParse.PesterTests/
      - name: dotnet publish
        run: |
          dotnet publish ./AngleParse/AngleParse.csproj -c Release
      - name: Modify module metadata
        shell: pwsh
        env:
          CommitTag: ${{ github.ref_name }}
        run: |
          $ErrorActionPreference = 'Stop'
          $moduleManifestPath = './AngleParse/bin/Release/AngleParse/AngleParse.psd1'
          $moduleVersion = $Env:CommitTag -replace '^v', ''
          
          filter modify($key, $value)
          {
              $_ -replace "^\s*$key\s*=.*$", "$key = '$value'"
          }

          Get-Content $moduleManifestPath |
                  modify ModuleVersion $moduleVersion |
                  Set-Content $moduleManifestPath
      - name: Publish to PowerShell Gallery
        shell: pwsh
        env:
          PSGalleryApiKey: ${{ secrets.PSGalleryApiKey }}
        run: |
          $ErrorActionPreference = 'Stop'
          $modulePath = './AngleParse/bin/Release/AngleParse'
          if (-not (Test-Path $modulePath)) {
            throw "Module path $modulePath does not exist."
          }
          Publish-Module -Path $modulePath -NuGetApiKey $env:PSGalleryApiKey